# Generated by Django 3.2.23 on 2023-12-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("home", "0001_load_initial_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="GGwsv",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jgj", models.BigIntegerField()),
                ("ewgs", models.BooleanField(blank=True, null=True)),
                ("gnv", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
